service: kinesis-consumer

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 3
  region: eu-west-1
  iamRoleStatements:
    - ${file(iam/DemoStreamIAM.yml):DemoStreamIAM}

functions:
  consumer:
    handler: src/handlers/consumer.handler
    name: kinesis-consumer
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - DemoStream
              - Arn
          parallelizationFactor: 2
  producer:
    handler: src/handlers/producer.handler
    name: kinesis-producer
    environment:
      STREAM_NAME: !Ref DemoStream
    events:
      - http:
          method: post
          path: producer

resources:
  Resources:
    DemoStream: ${file(resources/DemoStream.yml):DemoStream}
    DeadLetterQueue: ${file(resources/DLQ.yml):DeadLetterQueue}

plugins:
  - serverless-bundle
custom:
  bundle:
    linting: false